### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jimlunsford** [idmarinas/lotgd-game#1]
I tried to run the installer but when I did I got this error.

Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory in /home/******/*********/common.php on line 63

Fatal error: require_once(): Failed opening required 'vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php70/root/usr/share/pear') in /home/*******/********/common.php on line 63

(replaced directory names with *******)

**Comment by idmarinas** [comment]
You follow instructions? in: https://github.com/idmarinas/lotgd-game/wiki

First need install composer and npm, and them run gulp task.
