### ISSUE TITLE
unable to verify email address from gmail account

### ISSUE THREAD

**Issue by ahrib** [idmarinas/lotgd-game#1345]
**Describe the bug**
clicking link in email verification message does not work as expected.

Login name: jenk

In order to verify your account, you will need to click on the link below.

https://lotgd.infommo.es/create.php?op=val&id=16385502f4541c401878d76e223ab9ca

Thanks for playing!

**To Reproduce**
1. Create an account using a gmail email address
2. Wait for verification email
3. click link in verification email

> Your email could not be verified. This may be because you already validated your email. Try to log in, and if that doesn't help, use the 'Forgotten Password' option to retrieve a new mail. In case of all hope lost, use the petition link at the bottom of the page and provide ALL details with what you did and what info you got.

**Expected behavior**
account to be verified without issue

**Desktop (please complete the following information):**
 - OS: macOS 12.4
 - Browser Chrome v103

**Comment by idmarinas** [comment]
Hello, thank you for the report.

The error has been corrected and the email can be verified correctly.

This patch will be included in version 7.1.1 as well as being included in the online version.
