### ISSUE TITLE
Forgot Password does not work

### ISSUE THREAD

**Issue by ahrib** [idmarinas/lotgd-game#1346]
Describe the bug

I receive a forgot password email, however when clicking the link in the message I receive an error 

> Your request could not be verified. This may be because the link you used is invalid. Try to log in, and if that doesn't help, use the 'Forgotten Password' option to retrieve a new mail. In case of all hope lost, use the petition link at the bottom of the page and provide ALL details with what you did and what info you got.

_Originally posted by @ahrib in https://github.com/idmarinas/lotgd-game/issues/1342#issuecomment-1189847897_

**Comment by idmarinas** [comment]
Hello, thank you for the report.

The error has been corrected and the email can be verified correctly.

This patch will be included in version 7.1.1 as well as being included in the online version.
