### ISSUE TITLE
its a new day screen - missing added turns value

### ISSUE THREAD

**Issue by ahrib** [idmarinas/lotgd-game#1353]
**Describe the bug**

**To Reproduce**
1. Login
2. go to "its a new day" screen https://lotgd.infommo.es/newday.php?setspecialty=DA&c=40
3. Scroll down to 'You receive {added_turns}!'

**Expected behavior**
expect to see a value instead of template variable name e.g. 'You receive 1 turns!'

**Screenshots**
<img width="785" alt="Screen Shot 2022-07-29 at 5 33 49 pm" src="https://user-images.githubusercontent.com/2560650/181708540-e542042d-1005-465f-8d4a-ee687eba2c2e.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - Browser Chrome v103

**Comment by idmarinas** [comment]
Fixed, this path are include in version 0.1.3 of module https://github.com/lotgd-core/fund-drive-bundle
Next game update version include this fix.
