### ISSUE TITLE
graveyard - look for something to torment results in error 500

### ISSUE THREAD

**Issue by ahrib** [idmarinas/lotgd-game#1354]
**Describe the bug**

**To Reproduce**
1. have your character die
2. Click on places 'The Graveyard' https://lotgd.infommo.es/graveyard.php?op=search&c=175
3. Click on 'look for something to torment'

Server Error
We're sorry! The server encountered an internal error and was unable to complete your request. Please try again later.
error 500 | 29. 7. 2022 07:47

**Expected behavior**
no error

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - Browser: Chrome v103

**Comment by idmarinas** [comment]
Hello, thank you for the report.

The error has been fixed with other error in gardens.

This patch will be included in version 7.1.1 as well as being included in the online version.
