### ISSUE TITLE
Merick's Stables:  After buying pony, cannot sell nor trade up to stallion

### ISSUE THREAD

**Issue by chenagon** [idmarinas/lotgd-game#1495]
**Describe the bug**
Purchased a pony for 4 gems - have saved up 12 gems.  Unable to sell pony nor trade up and buy Stallion

**To Reproduce**
1. Have a pony and 12 gems
2. Go to Merick's Stables
3. Try either Sell your Pony and click "Yes" OR Examine Stallion > Buy this creature > "Yes"
4. Still have pony and 12 gems

**Expected behavior**
-Able to sell Pony and receive 4 gems
-Able to buy Stallion when have Pony and 12 gems

**Screenshots**
Merick_Stables_SellPony1, 2 = prompt to sell pony > click yes > after clicking - still have pony and gems
![Merick_Stables_SellPony1](https://user-images.githubusercontent.com/18216907/229633449-acb0908e-d59c-41af-954b-0c85993db47f.png)
![Merick_Stables_SellPony2](https://user-images.githubusercontent.com/18216907/229633452-768d7a5b-d743-4f71-82a1-87276ae9db9b.png)
Merick_Stables_BuyStallion1, 2, 3 = examine stallion > buy this creature > yes > after clicking - still have pony and gems
![Merick_Stables_BuyStallion1](https://user-images.githubusercontent.com/18216907/229633444-a3c53bc7-af96-47c9-9e55-2439e6687d31.png)
![Merick_Stables_BuyStallion2](https://user-images.githubusercontent.com/18216907/229633445-e091ad3b-3c82-4997-af95-227e4bd1b62b.png)
![Merick_Stables_BuyStallion3](https://user-images.githubusercontent.com/18216907/229633446-1052a628-534b-4e8a-9ad2-c464b09e8b9a.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by idmarinas** [comment]
Thx for your report, this bug are fixed.
