### ISSUE TITLE
Forest Event Stuck

### ISSUE THREAD

**Issue by chenagon** [idmarinas/lotgd-game#1500]
**Describe the bug**
In the forest of Glorfindal, received event where the options are Help, Hinder, or Ignore.  Clicking Help, receive 500 error

**To Reproduce**
1. Go to forest in Glorfindal
2. Receive random event where can Help, Hinder, or Ignore
3. Select Help
![image](https://user-images.githubusercontent.com/18216907/232237349-2bbb2564-44fb-403e-a281-44a86be48307.png)
![image](https://user-images.githubusercontent.com/18216907/232237359-db24aebd-8d5e-4bc4-a08d-a247e55e3e42.png)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by idmarinas** [comment]
Fixed it, thx for your report
