### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Sytrookie** [idmarinas/lotgd-game#1505]
**Describe the bug**
Error message: "[ERROR] We have detected that the version from "0.0.-2" or the version to "7.1.4" are not valid (one or both)."
When running install script `php bin/console lotgd:install`

When selecting any installation version or clean install presented with this error.

**Comment by idmarinas** [comment]
Thx for your report, I checking for find this error

**Comment by idmarinas** [comment]
Fixed, can download version 7.1.5 and you can install the game
