### ISSUE TITLE
Chances(Hit-Miss, Critical, Escape)

### ISSUE THREAD

**Issue by IamCanDoit** [idmarinas/lotgd-game#592]
I would like to see a clear way to calculate what is power move chance here. Normal hit chance, miss hit chance. I know there is e_rand(1,20) == 1 which is 5%, but the attack and defense still go through bell_rand and then when somehow all stars align, you get a chance to do power move.

Somekind of statistics would be nice. Total hits, missed hits, retaliation, critical... I think then this way there is chance to balance the game or add modifications like race or skill that modifies critical hit chance and power.

Thanks!

**Comment by idmarinas** [comment]
The game now show all results of round(s) if you use "Until end" see all miss, critical....
But, I see your sugestion, and But I want to change the whole battle to make it more expandable.
For now I'm working in translation system.
