### ISSUE TITLE
Expand the wiki?

### ISSUE THREAD

**Issue by jimlunsford** [idmarinas/lotgd-game#751]
I am trying to figure out how to install the game in a shared hosting environment. Is it possible? If it is and can be done could you please include it in the wiki?

**Comment by idmarinas** [comment]
I think that you can, you need use the lastest version, download zip file in "release" folder and uploads files and them run url https://yourserver.com/
The game redirect you to installer.

I will review the wiki to improve it.

But before installing the game you must make sure it meets the minimum requirements.

I think I will create a small script to make these checks easier and more automatic.
