### ISSUE TITLE
500 Server error

### ISSUE THREAD

**Issue by kahveciderin** [idmarinas/lotgd-game#783]
**Describe the bug**
pretty much nothing works. everything gives a 500 error

**To Reproduce**
1. Clone the repo to a web server
2. Check lotgd-check-requeriments-4.2.php (all green)
3. Go to public/installer.php or any file in the public dir

**Expected behavior**
It should work

**Screenshots**
None

**Server
Debian GNU/Linux 10 (buster) x86_64 
PHP 7.3.19-1~deb10u1 (cli) (built: Jul  5 2020 06:46:45) ( NTS )
MariaDB Server version: 10.3.23-MariaDB-0+deb10u1 Debian 10

**Additional context**

Server Error

We're sorry! The server encountered an internal error and was unable to complete your request. Please try again later.

error 500 | 2. 10. 2020 18:46
Tracy is unable to log error.

**Comment by idmarinas** [comment]
You downloaded laster zip? of https://github.com/idmarinas/lotgd-game/tree/master/release 

Clone this repo to server, not work. Use zip. 

The `storage/` folder needs http server read and write permission.

`Tracy is unable to log error.` this message is for this. But can check `storage/log/tracy` if have content.

**Comment by kahveciderin** [comment]
I have downloaded latest zip. The folder has those perms. storage/log/tracy/ is empty.

**Comment by idmarinas** [comment]
And the php log?

**Comment by kahveciderin** [comment]
nothing in there.

**Comment by idmarinas** [comment]
Nothing? no error log?
Without an error log, I don't know how to help you

**Comment by idmarinas** [comment]
Other option is disable Tracy logger. May be this show the real error.

I tell you 2 options:
Need alter the file `public/common.php`

First is put Tracy in development:
```php
// Change this line (21)
\Tracy\Debugger::enable($debuggerMode, __DIR__.'/../storage/log/tracy');
// TO
\Tracy\Debugger::enable(\Tracy\Debugger::DEVELOPMENT, __DIR__.'/../storage/log/tracy');
```
Second option is full disable Tracy.
```php
// Comment all this lines (18)
// $isDevelopment = file_exists('config/development.config.php');
// //-- Init Debugger
// $debuggerMode = $isDevelopment ? \Tracy\Debugger::DEVELOPMENT : \Tracy\Debugger::PRODUCTION;
// \Tracy\Debugger::enable($debuggerMode, __DIR__.'/../storage/log/tracy');
\Tracy\Debugger::timer('page-generating');
\Tracy\Debugger::timer('page-footer');
// \Tracy\Debugger::$maxDepth = 5; // default: 3
// //-- Extensions for Tracy
// if ($isDevelopment)
// {
//     \Tracy\Debugger::getBar()->addPanel(new \Milo\VendorVersions\Panel());
// }
```

Check with one of this options (or all), and tell me if now can see any error. To see if we can solve the problem.
